### ISSUE TITLE
resnet34 typo

### ISSUE THREAD

**Issue by Ben-Downes** [Lornatang/ResNet-PyTorch#1]
I noticed in utils.py that there is a typo with "resnet30" instead of "resnet34"

**Comment by Lornatang** [comment]
Thank you very much for your attention to my work. Where did this problem appear?

**Comment by Ben-Downes** [comment]
I was trying to use the tool but when I tried getting a resnet34 model it dropped a key error that there wasn't a rsenet34 in the various dicts.  Looking at the code I saw there was a "resnet30" in the keys instead.  I changed them to resnet34 in my local copy and it worked.

**Comment by Lornatang** [comment]
@Ben-Downes Thanks， They will fix .
