### ISSUE TITLE
I can't find the download location of the CIFAR dataset. I also tried to find it in Baidu Cloud.

### ISSUE THREAD

**Issue by wang1528186571** [Lornatang/ResNet-PyTorch#14]
I can't find the download location of the CIFAR dataset. I also tried to find it in Baidu Cloud.

**Comment by Lornatang** [comment]
CIFAR10: [Baidu Cloud](https://pan.baidu.com/s/1dYfVB7BDX-HYp56d-Ad7Mw?pwd=lorn)
CIFAR100: [Baidu Cloud](https://pan.baidu.com/s/1hlleCUP33vvUGeMqUbc1jA?pwd=lorn)
