### ISSUE TITLE
pip3 install -e . does not provide the resnet_pytorch anymore

### ISSUE THREAD

**Issue by AndreKelm** [Lornatang/ResNet-PyTorch#3]
Hello!
Thank you very much for the nice ResNet implementation! I have three questions: 
1.) Have you changed much in the last months? Because I think I do the same as before to install resnet-pytorch, but now there is an error message that there is no setup.py anymore (which is true :-)

This is what I did....
Install from source:
``bash
$ git clone https://github.com/Lornatang/ResNet-PyTorch.git
$ cd ResNet-PyTorch
$ pip3 install -e .

This was cool for me because I could create my own model there and put it into the timm framework (pytorch-image-models), so my own model would be loaded instead of the default one.

            from resnet_pytorch import ResNet              // with this I could include your resnet-pytorch github repo
            mymodel= ResNet.from_name("resnet50")    // with this I could load the changed model and replace it with the default loaded one

But now this doesn't work anymore. 
2nd) Do you have any idea how I can call your model now, For example when I am in another training environment (timm, pytorch-image-models)?
3rd) Could you provide me with the previous version? If still available, so that I can fork this version to my own github?

Thanks in advance!
André

**Comment by AndreKelm** [comment]
I found an older version and reinstalled it and after rebuild everything works again.

**Comment by Lornatang** [comment]
Sorry, I'm busy with other project...
