### ISSUE TITLE
Grayscale training

### ISSUE THREAD

**Issue by yuril123** [Lornatang/ResNet-PyTorch#4]
Is there a way to configure ResNet training for 1 channel images (grayscale)?

**Comment by Lornatang** [comment]
In `model.py` 136 line.

self.conv1 = nn.Conv2d(3, self.in_channels, (7, 7), (2, 2), (3, 3), bias=False)
**---change to----**
self.conv1 = nn.Conv2d(1, self.in_channels, (7, 7), (2, 2), (3, 3), bias=False)
